### ISSUE TITLE
JK Boston - nouvelle catégorie à créer

### ISSUE THREAD

**Issue by louberady** [wellsy-organization/projects#26]
1-Il faut créer une nouvelle "catégorie de produits" sur le site qui porterait le nom 
"**Baskets et sneakers personnalisées**"

2-Y intégrer le contenu SEO présent sur cette page
https://jk-boston.com/fr/personnalisez-vos-baskets-avec-j-k-boston/

3- Y intégrer des produits qui fit avec la catégories 
=> soit des baskets personnalisables 

4- supprimer les pages ci-dessous
https://jk-boston.com/fr/baskets-personnalisees-faire-le-choix-de-avec-j-k-boston/
https://jk-boston.com/fr/personnalisez-vos-baskets-avec-j-k-boston/

---------

Note à moi même : aller ajouter des occurences sur cette nouvelle catégorie 
et switch pour plus de "sneakers" au lieu de Baskets, sur 10 MC

**Comment by BenjaminSIP** [comment]
As-tu besoin de moi du coup car je pense qu'il n'y a pas de difficultés particulières pour ces demandes ?

**Comment by louberady** [comment]
oui :)

**Comment by BenjaminSIP** [comment]
Ah oui je vois que les 4 points sont liés à la création d'une nouvelle catégorie uniquement.
Comme j'avais expliqué à Olivier il y a quelques temps, je ne sais pas comment créer de nouvelles catégories et qu'elles soient pérennes dans le temps, car les catégories de produits ont été crées à partir de Bespoke Factory qui a été connecté à JK-Boston, donc il faudrait que Bespoke Factory créé cette nouvelle catégorie dans un premier temps. De plus, il y a plus de 1 700 produits donc je ne pourrais pas le faire manuellement non plus

Je vais demander à Bespoke Factory s'ils peuvent créer cette catégorie de leur côté et si c'est le cas je devrais relancer le flux de création de produits  entre bespoke et jk-boston afin de mettre à jour tous les produits du site et leurs catégories

**Comment by BenjaminSIP** [comment]
J'ai eu un retour de leur part, ils reviennent vers moi avec la procédure pour créer cette catégorie et attribuer les chaussures déjà existantes

**Comment by louberady** [comment]
Top merci !

**Comment by BenjaminSIP** [comment]
**Je te mets l'intégralité de l'échange avec le support de Bespoke Factory qui confirme que la création de cette catégorie de manière semi-automatisée (l'idée était que j'obtienne un fichier CSV afin d'appliquer la catégorie Sneakers aux produits déjà existants via un import permettant de mettre à jour les produits du site, ce qui aurait déjà pris quelques heures mais aurait été plus efficace que de le faire manuellement) :**


-----------------------------------------------------------------------------------------------------------------------
Hi Benjamin
If IT has already replied to you on this matter and provided possible technical solutions, their response is the authoritative one. They manage the functions of this type of file and handle the technical implementations.



Regards
Federico José Mano
Growth Specialist | Bespoke Factory Group

-----------------------------------------------------------------------------------------------------------------------

El mié, 18 sept 2024 a las 10:17, Benjamin GEORGES (<[benjamin@wellsy.io](mailto:benjamin@wellsy.io)>) escribió:
Hello,

[@Federico Jose Mano](mailto:fjmano@bespokefactory.com) could you please confirm that we cannot import only the sneakers on JK Boston website?

Because the 2 solutions provided from the support here won’t suit our needs because

Solution 1: We don’t want to sell only sneakers
Solution 2: It doesn’t seem like there is any column that contains the word sneakers to be able to filter these within Excel


Our goal is to be able to create a Sneakers category on the website but we don’t want to go through each 1700 products and manually attribute each product to this category.


Let me know if you can think of any solution regarding this matter.

Thank you,
Benjamin Georges


-----------------------------------------------------------------------------------------------------------------------


De : Bespoke Factory - Customer Service <[customerservice@bespokefactory.com](mailto:customerservice@bespokefactory.com)>
Date : mercredi, 18 septembre 2024 à 06:33
À : Benjamin GEORGES <[benjamin@wellsy.io](mailto:benjamin@wellsy.io)>
Objet : Re: “sneakers” category [#702551]

-- Please, reply above this line --

Hi Benjamin,

We don't have a way to apply filters to the CSV automatically in the service.
Or actually we have, but it depends on the active models at the account, meaning that if you had all styles disabled except for sneakers then the CSV would only contain those styles, but at the same time the configurator wouldn't display anything else, so the account would only sell sneakers.
If that's what you want, go ahead with that solution.
Otherwise you can always download the complete CSV, open it and filter the data for only what you need.


Best regards,

--

Raúl Loza

Chief Frontend Development
> Tech Department
> > Bespoke Factory Group 

-----------------------------------------------------------------------------------------------------------------------

Hello,

I need a CSV file that only includes sneakers.

Thank you,
Benjamin

-----------------------------------------------------------------------------------------------------------------------

Hi Benjamin,

Yes, we have a few services that might come in handy.
If you are planning on introducing pre-designed items such as our Get Inspired platform, you can get the CSV from here: https://jkboston.made-to-order.com/membership.aspx#getinspired
Otherwise, if you plan to have entrypoints to the configurator directly, you can use this CSV: https://backoffice.bespokefactory.com/services/csv/configurator-catalog-importation.aspx?jb=eyJpZGMiOjE5MjAyLCJrIjoiNDc1MmI1ZGIifQ==


Hope that helps!



--
Raúl Loza

Chief Frontend Development
> Tech Department
> > Bespoke Factory Group


-----------------------------------------------------------------------------------------------------------------------

Sure, I'll submit a ticket to IT so they can address this. I know we have a CSV file available, and it’s possible to filter the style you need from there. However, I’d prefer for them to provide a more accurate response.

Regards
Federico José Mano

-----------------------------------------------------------------------------------------------------------------------


Hello Federico,

I would like to know if that is possible to create a “sneakers” category on the website, there are too many products to do it manually, so I was wondering if Bespoke Factory might have a CSV file including this category?

Thank you,
Benjamin

**Comment by louberady** [comment]
La compréhension que j'ai de cet échange est que ce n'est pas possible. Car le CSV ne te permet pas de filtrer uniquement les baskets personnalisable. Et manuellement ça prendrait trop de temps. 
C'est ça ?

**Comment by BenjaminSIP** [comment]
C'est ça

**Comment by louberady** [comment]
L'équipe technique est repassé sur **les 3 catégories optimisées**, ils ont mis les contenus intégrés en bas de page dans le "champ classique".

Détails des pages catégories concernées :

- https://jk-boston.com/fr/categorie-de-produits/chaussures-pour-hommes/
- https://jk-boston.com/fr/categorie-de-produits/chaussures-pour-femmes/
- https://jk-boston.com/fr/categorie-de-produits/patine-faite-a-la-main/

![Image](https://github.com/user-attachments/assets/b8bf65d8-74eb-4a61-8083-3402b82380c4)

**Comment by BenjaminSIP** [comment]
C'est fait pour cette issue, je la réouvre car elle était fermée, puis je la passe en to review

**Comment by louberady** [comment]
Est il possible que tu fasses les redirections des pages du point **4-**

- https://jk-boston.com/fr/baskets-personnalisees-faire-le-choix-de-avec-j-k-boston/
- https://jk-boston.com/fr/personnalisez-vos-baskets-avec-j-k-boston/ 

vers la création de page du point **1-** ?

**Comment by BenjaminSIP** [comment]
Besoin de faire les redirections des versions anglaises aussi ou pas ?

**Comment by louberady** [comment]
je place l'issue en done

**Comment by BenjaminSIP** [comment]
Les redirections ne sont pas encore faites
